server:
  port: 12345

lesson:
  count: 20
  name: meiyo


spring:
  datasource:
    username: root
    password: Ty123456
    url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.tuya.lesson.java.entity
  mapper-default-scope:



# https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  # 分页合理化参数，默认值为false。默认false 时，直接根据参数进行查询。
  # 当该参数设置为 true 时：
  # pageNum<=0 时会查询第一页，
  # pageNum>pages（超过总数时），会查询最后一页。
  reasonable: true
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。
  helperDialect: mysql
  # 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  supportMethodsArguments: true
  #  为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable
  #  params: count=countSql

# mybatis 日志打印
logging:
  level:
    com.tuya.lesson.java.dao: DEBUG